#!/bin/bash

# 修复 OSS Bucket 问题

echo "=========================================="
echo "  OSS Bucket 问题修复指南"
echo "=========================================="
echo ""

BUCKET="ai-host"
REGION="oss-ap-southeast-1"
ORIGIN="https://cling-ai.com"

echo "当前使用的 Bucket: $BUCKET ($REGION)"
echo ""
echo "请确认该 Bucket 在阿里云控制台已存在并开启公共读或具备 STS 上传权限。"
echo ""

echo "=========================================="
echo "解决方案：创建 OSS Bucket"
echo "=========================================="
echo ""

echo "方法 1: 通过阿里云控制台创建（推荐）"
echo "----------------------------------------"
echo "1. 访问: https://oss.console.aliyun.com/"
echo "2. 点击左侧菜单: 存储空间（Bucket）"
echo "3. 点击右上角: 创建 Bucket"
echo "4. 填写配置："
echo "   - Bucket 名称: $BUCKET"
echo "   - 地域: 华东1（杭州）"
echo "   - 读写权限: 公共读（或私有，根据需求）"
echo "   - 其他选项: 使用默认值"
echo "5. 点击: 确定"
echo ""

echo "方法 2: 使用阿里云 CLI 创建"
echo "----------------------------------------"
echo "如果已安装阿里云 CLI，可以运行："
echo ""
echo "aliyun oss mb oss://$BUCKET --region $REGION"
echo ""

echo "=========================================="
echo "创建 Bucket 后，配置 CORS"
echo "=========================================="
echo ""
echo "1. 在 OSS 控制台选择 bucket: $BUCKET"
echo "2. 进入: 权限管理 -> 跨域设置（CORS）"
echo "3. 点击: 创建规则"
echo "4. 填写 CORS 配置："
echo ""
echo "   来源（AllowedOrigins）:"
echo "     $ORIGIN"
echo "     http://localhost:5173"
echo "     http://localhost:3000"
echo ""
echo "   允许 Methods（全部勾选，控制台不会显示 OPTIONS）:"
echo "     ✅ GET"
echo "     ✅ PUT      ← 最重要！"
echo "     ✅ POST"
echo "     ✅ HEAD"
echo "     ✅ DELETE"
echo "   （OSS 会自动响应 OPTIONS 预检，这里只需要列出真实请求动词）"
echo ""
echo "   允许 Headers:"
echo "     *"
echo ""
echo "   暴露 Headers:"
echo "     ETag"
echo "     x-oss-request-id"
echo "     x-oss-next-append-position"
echo ""
echo "   缓存时间（秒）:"
echo "     3600"
echo ""
echo "5. 点击: 确定"
echo "6. 等待 1-5 分钟让配置生效"
echo ""

echo "=========================================="
echo "验证步骤"
echo "=========================================="
echo ""
echo "创建 Bucket 并配置 CORS 后，运行以下命令验证："
echo ""
echo "  ./deploy/diagnose_oss_upload.sh"
echo ""
echo "应该看到："
echo "  ✅ CORS 配置存在"
echo "  ✅ Origin 匹配正确"
echo ""

echo "=========================================="

